DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS musique;
DROP TABLE IF EXISTS album;
DROP TABLE IF EXISTS artist;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE musique (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  track_number INTEGER NOT NULL,
  album_id INTEGER NOT NULL,
  artist_id INTEGER NOT NULL,
  FOREIGN KEY (album_id) REFERENCES album (id),
  FOREIGN KEY (artist_id) REFERENCES artist (id)
);

CREATE TABLE album (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  artist_id INTEGER NOT NULL,
  year INTEGER NOT NULL,
  cover_path TEXT NOT NULL,
  FOREIGN KEY (artist_id) REFERENCES artist (id)
);

CREATE TABLE artist (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL
);
